services:
  - type: web
    name: hackabhigna-backend
    runtime: node
    buildCommand: apt-get update && apt-get install -y texlive-latex-base texlive-latex-extra texlive-fonts-recommended && cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: ATLAS_URI
        sync: false
      - key: SENDGRID_API_KEY
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: GITHUB_OWNER
        sync: false
      - key: GITHUB_TOKEN
        sync: false
      - key: VITE_GITHUB_OWNER
        sync: false
      - key: VITE_GITHUB_TOKEN
        sync: false
      - key: NODE_ENV
        value: production
    healthCheckPath: /health
